### ISSUE TITLE
Can you upload a non-moonscript example?

### ISSUE THREAD

**Issue by oconnore** [Configi/configi#4]
I keep getting the same output no matter what I put in config.lua:

```
bin/cfg -vf config.lua 
Started run 2016-11-06 00:44:46 MDT-0600
Applying policy: ./config.lua
------------
Kept: true
Finished run in 0 seconds
```

So far I've tried

```
file.touch("hello", {
  comment = "what",
  handle = "touch"
})
```

```
file.touch("hello") {
  comment = "what",
  handle = "touch"
}
```

```
file.touch "hello" {
  comment = "what",
  handle = "touch"
}
```

```
file.touchyyyy "hello" {
  comment = "what",
  handle = "touch"
}

file.nopenopenpe("hello", {
  comment = "what",
  handle = "touch"
})
```

And I never get a file, or even any different output when I call a bogus module.

Also, I don't know how moonscript works, but when I copy/paste the example from the website, I get:

```
$ ./bin/cfg -vf policy 
[string "configi"]:626: attempt to index a nil value (field '?')
$ cat policy
file.directory"/tmp/dir"
  comment: "Create directory if running on Gentoo"
  context: fact.osfamily.gentoo
  mode: "0700"
  notify: "touch"

yum.present"mtr"
  context: fact.osfamily.centos

file.absent"/tmp/dir"
  notify: "touch"

file.touch"/tmp/dir"
  comment: "Handle 'touch' notifications. This is only executed once."
  handle: "touch"
```

**Comment by oconnore** [comment]
I figured out how to write policy .lua files (`<module>.<function>(<subject>){ <arg> = <value> ... }`, but I think the second thing is still a bug?

**Comment by tongson** [comment]
Hello!

Thanks for trying out Configi.

That is the correct way to write a Lua policy. A `handle` parameter denotes a handler so that requires a `notify` to call it.

Yes looks like the second issue is a bug. Configi is looking for policy.moon or policy.lua. I think it should default to MoonScript if the policy file has no extension.

Cheers.

**Comment by tongson** [comment]
Going to retract MoonScript support.
The parser is larger than Configi core and plain Lua policies are already pretty good.

Going to expand OpenWRT/LEDE/embedded support so code removal is a plus.
